CXX = g++

Q3: 
	$(CXX) mainQ3.cpp Grid.cpp minisat/*.cpp
Q4:
	$(CXX) mainQ4.cpp Grid.cpp minisat/*.cpp
Q5:
	$(CXX) mainQ5.cpp Grid.cpp minisat/*.cpp
Q6:
	$(CXX) mainQ6.cpp Grid3D.cpp minisat/*.cpp
Q7:
	$(CXX) mainQ7.cpp Grid3D.cpp minisat/*.cpp