CXX = g++

Q3: 
	$(CXX) -std=c++11 mainQ3.cpp Grid.cpp minisat/*.cpp
Q4:
	$(CXX) -std=c++11 mainQ4.cpp Grid.cpp minisat/*.cpp
Q5:
	$(CXX) -std=c++11 mainQ5.cpp Grid.cpp minisat/*.cpp
Q6:
	$(CXX) -std=c++11 mainQ6.cpp Grid3D.cpp minisat/*.cpp
Q7:
	$(CXX) -std=c++11 mainQ7.cpp Grid3D.cpp minisat/*.cpp